name: Deploy Firebase (Template)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "site/**"
      - ".github/workflows/firebase.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -g firebase-tools
      - run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
